### PR TITLE
feat: check image compliance

### PR DESCRIPTION
**Pull request by tenthirtyam**
### Summary

Adds `-checkImageCompliance` to `Get-VCFCluster`.

Cherry-picked for @nthaler-vmware.

### Type

- [ ] Bugfix
- [x] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [x] Documentation has been added or updated.

### CODE REVIEW

**Comment by LifeOfBrianOC** [comment]
Code looks good. Just one question back to Nathan on behaviour when the cluster is VUM-based

**Comment by nathanthaler** [comment]
> Code looks good. Just one question back to Nathan on behaviour when the cluster is VUM-based

Agreed.  Adding additional checking to provide a more user friendly error.

**Comment by tenthirtyam** [comment]
I've pushed an update (7c7eef5) that does the following:

- Makes the `id` and `name` parameters mutually exclusive.
- Brings in the suggested change by Nathan (@nthaler-vmware) and Brian (@LifeOfBrianOC) to check if the cluster is vLCM imaged based.
- Removes `uri` redundancies.
- Removes `$response` redundancies.
- Trims trailing spaces.

@nthaler-vmware - please also review and test the new capability and for any regressions.

**Comment by tenthirtyam** [comment]
@nthaler-vmware - do you want to continue with this pull request?

**Pull request closed without merging**
