### PR TITLE
feat: add `-id` and `-vdses` options to `Get-VcfCluster`

### PR DESCRIPTION
**Pull request by LifeOfBrianOC**
### Summary

Added a switch to `Get-VCFCluster` to retrieve VDS detail.

### Type

- [ ] Bugfix
- [x] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [x] Documentation has been added or updated.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Can you cherry-pick the commit from the other branch to add the change to the function and docs in the same pull request?

Let me know if you need help with it.

**Comment by LifeOfBrianOC** [comment]
> Can you cherry-pick the commit from the other branch to add the change to the function and docs in the same pull request?
> 
> Let me know if you need help with it.

Done. Not sure how they got split up

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
LGTM! 

Could you bump the build for the module version and update the `CHANGELOG.md`?

**Review by tenthirtyam — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
