### PR TITLE
feat: add `Get-VCFLicenseMode` cmdlet

### PR DESCRIPTION
**Pull request by LifeOfBrianOC**
In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/PowerVCF/PowerVCF/blob/master/CONTRIBUTING.md) for making a pull request.

## Summary of Pull Request

Adding cmdlet to retrieve the license mode (subscription or perpetual)

## Type of Pull Request

- [ ] This is a bugfix.
- [x] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

## Context of the Pull Request

Adding cmdlet to retrieve the license mode (subscription or perpetual)

## Related to Existing Issues

no

Issue Number: N/A

## Test and Documentation Coverage

- [x] Tests have been completed (for bugfixes / features).
- [x] Documentation has been added / updated (for bugfixes / features).

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — APPROVED** [review]
LGTM! Just need to amend the commit with a sign-off.

Example:

```
Signed-off-by: Ryan Johnson <johnsonryan@vmware.com>
```

**Comment by GaryJBlake** [comment]
@LifeOfBrianOC can you also bump the build number in the PowerVCF.psd1

**Review by tenthirtyam — APPROVED** [review]
LGTM! 🚀

**Review by GaryJBlake — APPROVED** [review]
LGTM!

**Pull request merged**
